//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport_asssignment_H3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirlineNetworkEntities2 : DbContext
    {
        public AirlineNetworkEntities2()
            : base("name=AirlineNetworkEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airlines> Airlines { get; set; }
        public virtual DbSet<Airport> Airport { get; set; }
        public virtual DbSet<AirportRoutes> AirportRoutes { get; set; }
        public virtual DbSet<Operates> Operates { get; set; }
    }
}
